name: First Workflow

on:
  pull_request:
    types:
      - opened

jobs:
  generate_data:
    runs-on: ubuntu-latest

    steps:
    - name: Generate UUID
      id: generate-uuid
      run: echo "::set-output name=uuid::$(uuidgen)"

    - name: Save UUID to file
      run: echo "${{ steps.generate-uuid.outputs.uuid }}" > uuid.txt

    - name: Cache UUID
      uses: actions/cache@v2
      with:
        path: uuid.txt
        key: uuid-${{ github.run_id }}
        restore-keys: |
          uuid-${{ github.run_id }}
