name: First Workflow

on:
  pull_request:
    branches:
      - feature/*
    types:
      - opened

jobs:
  generate_uuid:
    runs-on: ubuntu-latest

    steps:
    - name: Generate UUID
      id: generate-uuid
      run: echo "::set-output name=uuid::$(uuidgen)"
      
    - name: Save UUID to file
      run: echo "${{ steps.generate-uuid.outputs.uuid }}" > uuid.txt

    - name: Upload UUID as artifact
      uses: actions/upload-artifact@v2
      with:
        name: uuid-artifact-${{ github.event.pull_request.number }}
        path: uuid.txt
