name: First Workflow

on:
  pull_request:
    types:
      - opened

jobs:
  add_comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate UUID
      id: generate-uuid
      run: echo "::set-output name=uuid::$(uuidgen)"

    - name: Add comment with UUID
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "Generated-UUID: ${{ steps.generate-uuid.outputs.uuid }}"
      env:
        GH_TOKEN: ${{ secrets.GWR_GH_TOKEN }}
