name: Second Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  retrieve_uuid:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch UUID from PR comment
      run: |
        COMMENTS=$(gh pr view ${{ github.event.pull_request.number }} --json comments -q '.comments[].body')
        UUID=$(echo "$COMMENTS" | grep "Generated-UUID:" | awk '{print $2}')
        echo "UUID: $UUID"
      env:
        GH_TOKEN: ${{ secrets.GWR_GH_TOKEN }}
