name: Deploy to dev after merge
on:
  pull_request:
    types:
      - closed

jobs:
  Run-Salto-Deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Download datetime artifact
      uses: actions/download-artifact@v2
      with:
        name: datetime-artifact

    - name: Cat saved date and time
      run: cat datetime.txt
