name: Second Workflow

on:
  pull_request_review:
    types:
      - submitted
    branches:
      - main

jobs:
  echo_saved_uuid:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    
    steps:
    - name: Download UUID artifact
      uses: actions/download-artifact@v2
      with:
        name: uuid-artifact-${{ github.event.pull_request.number }}

    - name: Cat saved UUID
      run: cat uuid.txt
